version: '3'
services:

  postgres:
    image: 'postgres'
    container_name: postgres
    networks:
      - application-network
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cloud
    ports:
      - 5432:5432
    tty: true
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  webapp:
    build: .
    ports:
      - "8081:8081"
    tty: true
    networks:
      - application-network
    environment:
      POSTGES_CONNECTION_STING : root
      DATABASE_DOMAIN: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      POSTGRES_DB: cloud
    depends_on:
      - postgres
networks:
  application-network:

volumes:
  postgres-data:





